FROM elixir:1.5.1

RUN apt-get update -qq && \
    apt-get install -y \
      build-essential \
      vim \
      git \
      libpq-dev \
      postgresql-client-9.4

ENV APP_HOME=/usr/src/click-api/
WORKDIR $APP_HOME

COPY mix* $APP_HOME
RUN mix local.hex --force
RUN mix local.rebar --force
RUN mix deps.get

COPY config $APP_HOME/config
RUN cp config/dev.local.docker.exs config/dev.local.exs
RUN mix deps.compile

COPY . $APP_HOME
RUN cp config/dev.local.docker.exs config/dev.local.exs
RUN mix compile
